// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.7.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -411632102;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api_atproto__api_cbor_encode_record_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_cbor_encode_record",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_record =
                <crate::atproto::lexicon::LexiconRecord>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api_atproto::api_cbor_encode_record(api_record)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api_atproto__api_compute_cid_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_compute_cid",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_cbor_bytes = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api_atproto::api_compute_cid(api_cbor_bytes))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api_crdt__api_crdt_apply_delta_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_crdt_apply_delta",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_entity_id = <String>::sse_decode(&mut deserializer);
            let api_payload_b64 = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok =
                    crate::api_crdt::api_crdt_apply_delta(api_entity_id, api_payload_b64)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api_crdt__api_crdt_get_text_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_crdt_get_text",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_entity_id = <String>::sse_decode(&mut deserializer);
            let api_field_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api_crdt::api_crdt_get_text(api_entity_id, api_field_name)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api_crdt__api_crdt_init_doc_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_crdt_init_doc",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_entity_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api_crdt::api_crdt_init_doc(api_entity_id);
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api_crdt__api_crdt_insert_text_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_crdt_insert_text",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_entity_id = <String>::sse_decode(&mut deserializer);
            let api_field_name = <String>::sse_decode(&mut deserializer);
            let api_content = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api_crdt::api_crdt_insert_text(
                    api_entity_id,
                    api_field_name,
                    api_content,
                )?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api_atproto__api_create_did_plc_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_create_did_plc",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_signing_key_hex = <String>::sse_decode(&mut deserializer);
            let api_handle = <String>::sse_decode(&mut deserializer);
            let api_pds_endpoint = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api_atproto::api_create_did_plc(
                    api_signing_key_hex,
                    api_handle,
                    api_pds_endpoint,
                )?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__api_decode_did_key_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_decode_did_key",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_did = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::api_decode_did_key(api_did)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__api_encode_did_key_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_encode_did_key",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_public_key_hex = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::api_encode_did_key(api_public_key_hex)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__api_generate_keypair_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_generate_keypair",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::api_generate_keypair())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api_messenger__api_messenger_create_device_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_messenger_create_device",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_subject_did = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api_messenger::api_messenger_create_device(api_subject_did)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api_messenger__api_messenger_decrypt_inbound_message_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_messenger_decrypt_inbound_message",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_local_device =
                <crate::messenger::MessengerDevice>::sse_decode(&mut deserializer);
            let api_ciphertext =
                <crate::messenger::MessengerCiphertext>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api_messenger::api_messenger_decrypt_inbound_message(
                        api_local_device,
                        api_ciphertext,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api_messenger__api_messenger_encrypt_initial_message_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_messenger_encrypt_initial_message",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_input =
                <crate::messenger::MessengerEncryptInput>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok =
                        crate::api_messenger::api_messenger_encrypt_initial_message(api_input)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api_messenger__api_messenger_generate_pre_keys_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_messenger_generate_pre_keys",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_device = <crate::messenger::MessengerDevice>::sse_decode(&mut deserializer);
            let api_count = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok =
                    crate::api_messenger::api_messenger_generate_pre_keys(api_device, api_count)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api_atproto__api_sign_commit_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_sign_commit",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_cbor_bytes = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_private_key_hex = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok =
                        crate::api_atproto::api_sign_commit(api_cbor_bytes, api_private_key_hex)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__api_sign_message_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_sign_message",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_private_key_hex = <String>::sse_decode(&mut deserializer);
            let api_message_hex = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok =
                        crate::api::api_sign_message(api_private_key_hex, api_message_hex)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__api_verify_signature_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_verify_signature",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_public_key_hex = <String>::sse_decode(&mut deserializer);
            let api_message_hex = <String>::sse_decode(&mut deserializer);
            let api_signature_hex = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::api_verify_signature(
                    api_public_key_hex,
                    api_message_hex,
                    api_signature_hex,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api_zkp__api_zkp_compute_nullifier_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_zkp_compute_nullifier",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_passport_secret_hex = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api_zkp::api_zkp_compute_nullifier(api_passport_secret_hex)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api_zkp__api_zkp_generate_proof_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_zkp_generate_proof",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_passport_secret_hex = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok =
                        crate::api_zkp::api_zkp_generate_proof(api_passport_secret_hex)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api_zkp__api_zkp_verify_proof_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "api_zkp_verify_proof",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_proof_hex = <String>::sse_decode(&mut deserializer);
            let api_nullifier_hex = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok =
                        crate::api_zkp::api_zkp_verify_proof(api_proof_hex, api_nullifier_hex)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::did_key::KeyPairBytes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_privateKeyHex = <String>::sse_decode(deserializer);
        let mut var_publicKeyHex = <String>::sse_decode(deserializer);
        let mut var_did = <String>::sse_decode(deserializer);
        return crate::did_key::KeyPairBytes {
            private_key_hex: var_privateKeyHex,
            public_key_hex: var_publicKeyHex,
            did: var_did,
        };
    }
}

impl SseDecode for crate::atproto::lexicon::LexiconRecord {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_type = <String>::sse_decode(deserializer);
        let mut var_text = <String>::sse_decode(deserializer);
        let mut var_createdAt = <String>::sse_decode(deserializer);
        let mut var_replyTo = <Option<String>>::sse_decode(deserializer);
        return crate::atproto::lexicon::LexiconRecord {
            type_: var_type,
            text: var_text,
            created_at: var_createdAt,
            reply_to: var_replyTo,
        };
    }
}

impl SseDecode for Vec<crate::messenger::MessengerPreKey> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::messenger::MessengerPreKey>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::messenger::MessengerCiphertext {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_protocolVersion = <String>::sse_decode(deserializer);
        let mut var_ciphertextType = <String>::sse_decode(deserializer);
        let mut var_ciphertext = <Vec<u8>>::sse_decode(deserializer);
        let mut var_updatedSessionState = <String>::sse_decode(deserializer);
        return crate::messenger::MessengerCiphertext {
            protocol_version: var_protocolVersion,
            ciphertext_type: var_ciphertextType,
            ciphertext: var_ciphertext,
            updated_session_state: var_updatedSessionState,
        };
    }
}

impl SseDecode for crate::messenger::MessengerDevice {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_subjectDid = <String>::sse_decode(deserializer);
        let mut var_deviceId = <String>::sse_decode(deserializer);
        let mut var_identityKeyPublic = <String>::sse_decode(deserializer);
        let mut var_identityKeyPrivate = <String>::sse_decode(deserializer);
        let mut var_signedPreKeyId = <u32>::sse_decode(deserializer);
        let mut var_signedPreKeyPublic = <String>::sse_decode(deserializer);
        let mut var_signedPreKeyPrivate = <String>::sse_decode(deserializer);
        let mut var_signedPreKeySignature = <String>::sse_decode(deserializer);
        let mut var_sessionState = <Option<String>>::sse_decode(deserializer);
        let mut var_oneTimePreKeys =
            <Vec<crate::messenger::MessengerPreKey>>::sse_decode(deserializer);
        let mut var_nextPreKeyId = <u32>::sse_decode(deserializer);
        return crate::messenger::MessengerDevice {
            subject_did: var_subjectDid,
            device_id: var_deviceId,
            identity_key_public: var_identityKeyPublic,
            identity_key_private: var_identityKeyPrivate,
            signed_pre_key_id: var_signedPreKeyId,
            signed_pre_key_public: var_signedPreKeyPublic,
            signed_pre_key_private: var_signedPreKeyPrivate,
            signed_pre_key_signature: var_signedPreKeySignature,
            session_state: var_sessionState,
            one_time_pre_keys: var_oneTimePreKeys,
            next_pre_key_id: var_nextPreKeyId,
        };
    }
}

impl SseDecode for crate::messenger::MessengerEncryptInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_localDevice = <crate::messenger::MessengerDevice>::sse_decode(deserializer);
        let mut var_remoteBundle =
            <crate::messenger::MessengerPreKeyBundle>::sse_decode(deserializer);
        let mut var_plaintext = <Vec<u8>>::sse_decode(deserializer);
        return crate::messenger::MessengerEncryptInput {
            local_device: var_localDevice,
            remote_bundle: var_remoteBundle,
            plaintext: var_plaintext,
        };
    }
}

impl SseDecode for crate::messenger::MessengerPlaintext {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_body = <Vec<u8>>::sse_decode(deserializer);
        let mut var_updatedSessionState = <String>::sse_decode(deserializer);
        return crate::messenger::MessengerPlaintext {
            body: var_body,
            updated_session_state: var_updatedSessionState,
        };
    }
}

impl SseDecode for crate::messenger::MessengerPreKey {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_preKeyId = <u32>::sse_decode(deserializer);
        let mut var_publicKey = <String>::sse_decode(deserializer);
        let mut var_privateKey = <String>::sse_decode(deserializer);
        return crate::messenger::MessengerPreKey {
            pre_key_id: var_preKeyId,
            public_key: var_publicKey,
            private_key: var_privateKey,
        };
    }
}

impl SseDecode for crate::messenger::MessengerPreKeyBundle {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_subjectDid = <String>::sse_decode(deserializer);
        let mut var_deviceId = <String>::sse_decode(deserializer);
        let mut var_identityKey = <String>::sse_decode(deserializer);
        let mut var_signedPreKeyId = <u32>::sse_decode(deserializer);
        let mut var_signedPreKey = <String>::sse_decode(deserializer);
        let mut var_signedPreKeySignature = <String>::sse_decode(deserializer);
        let mut var_oneTimePreKeyId = <u32>::sse_decode(deserializer);
        let mut var_oneTimePreKey = <String>::sse_decode(deserializer);
        return crate::messenger::MessengerPreKeyBundle {
            subject_did: var_subjectDid,
            device_id: var_deviceId,
            identity_key: var_identityKey,
            signed_pre_key_id: var_signedPreKeyId,
            signed_pre_key: var_signedPreKey,
            signed_pre_key_signature: var_signedPreKeySignature,
            one_time_pre_key_id: var_oneTimePreKeyId,
            one_time_pre_key: var_oneTimePreKey,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::atproto::did_plc::PlcGenesisOp {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_did = <String>::sse_decode(deserializer);
        let mut var_genesisJson = <String>::sse_decode(deserializer);
        return crate::atproto::did_plc::PlcGenesisOp {
            did: var_did,
            genesis_json: var_genesisJson,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api_zkp::ZkpResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_proofHex = <String>::sse_decode(deserializer);
        let mut var_nullifierHex = <String>::sse_decode(deserializer);
        let mut var_vkHash = <String>::sse_decode(deserializer);
        return crate::api_zkp::ZkpResult {
            proof_hex: var_proofHex,
            nullifier_hex: var_nullifierHex,
            vk_hash: var_vkHash,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => {
            wire__crate__api_atproto__api_cbor_encode_record_impl(port, ptr, rust_vec_len, data_len)
        }
        12 => wire__crate__api_messenger__api_messenger_decrypt_inbound_message_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        13 => wire__crate__api_messenger__api_messenger_encrypt_initial_message_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        15 => wire__crate__api_atproto__api_sign_commit_impl(port, ptr, rust_vec_len, data_len),
        16 => wire__crate__api__api_sign_message_impl(port, ptr, rust_vec_len, data_len),
        19 => wire__crate__api_zkp__api_zkp_generate_proof_impl(port, ptr, rust_vec_len, data_len),
        20 => wire__crate__api_zkp__api_zkp_verify_proof_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        2 => wire__crate__api_atproto__api_compute_cid_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api_crdt__api_crdt_apply_delta_impl(ptr, rust_vec_len, data_len),
        4 => wire__crate__api_crdt__api_crdt_get_text_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api_crdt__api_crdt_init_doc_impl(ptr, rust_vec_len, data_len),
        6 => wire__crate__api_crdt__api_crdt_insert_text_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api_atproto__api_create_did_plc_impl(ptr, rust_vec_len, data_len),
        8 => wire__crate__api__api_decode_did_key_impl(ptr, rust_vec_len, data_len),
        9 => wire__crate__api__api_encode_did_key_impl(ptr, rust_vec_len, data_len),
        10 => wire__crate__api__api_generate_keypair_impl(ptr, rust_vec_len, data_len),
        11 => wire__crate__api_messenger__api_messenger_create_device_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        14 => wire__crate__api_messenger__api_messenger_generate_pre_keys_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        17 => wire__crate__api__api_verify_signature_impl(ptr, rust_vec_len, data_len),
        18 => wire__crate__api_zkp__api_zkp_compute_nullifier_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::did_key::KeyPairBytes {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.private_key_hex.into_into_dart().into_dart(),
            self.public_key_hex.into_into_dart().into_dart(),
            self.did.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::did_key::KeyPairBytes {}
impl flutter_rust_bridge::IntoIntoDart<crate::did_key::KeyPairBytes>
    for crate::did_key::KeyPairBytes
{
    fn into_into_dart(self) -> crate::did_key::KeyPairBytes {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::atproto::lexicon::LexiconRecord {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.type_.into_into_dart().into_dart(),
            self.text.into_into_dart().into_dart(),
            self.created_at.into_into_dart().into_dart(),
            self.reply_to.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::atproto::lexicon::LexiconRecord
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::atproto::lexicon::LexiconRecord>
    for crate::atproto::lexicon::LexiconRecord
{
    fn into_into_dart(self) -> crate::atproto::lexicon::LexiconRecord {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::messenger::MessengerCiphertext {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.protocol_version.into_into_dart().into_dart(),
            self.ciphertext_type.into_into_dart().into_dart(),
            self.ciphertext.into_into_dart().into_dart(),
            self.updated_session_state.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::messenger::MessengerCiphertext
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::messenger::MessengerCiphertext>
    for crate::messenger::MessengerCiphertext
{
    fn into_into_dart(self) -> crate::messenger::MessengerCiphertext {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::messenger::MessengerDevice {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.subject_did.into_into_dart().into_dart(),
            self.device_id.into_into_dart().into_dart(),
            self.identity_key_public.into_into_dart().into_dart(),
            self.identity_key_private.into_into_dart().into_dart(),
            self.signed_pre_key_id.into_into_dart().into_dart(),
            self.signed_pre_key_public.into_into_dart().into_dart(),
            self.signed_pre_key_private.into_into_dart().into_dart(),
            self.signed_pre_key_signature.into_into_dart().into_dart(),
            self.session_state.into_into_dart().into_dart(),
            self.one_time_pre_keys.into_into_dart().into_dart(),
            self.next_pre_key_id.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::messenger::MessengerDevice
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::messenger::MessengerDevice>
    for crate::messenger::MessengerDevice
{
    fn into_into_dart(self) -> crate::messenger::MessengerDevice {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::messenger::MessengerEncryptInput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.local_device.into_into_dart().into_dart(),
            self.remote_bundle.into_into_dart().into_dart(),
            self.plaintext.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::messenger::MessengerEncryptInput
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::messenger::MessengerEncryptInput>
    for crate::messenger::MessengerEncryptInput
{
    fn into_into_dart(self) -> crate::messenger::MessengerEncryptInput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::messenger::MessengerPlaintext {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.body.into_into_dart().into_dart(),
            self.updated_session_state.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::messenger::MessengerPlaintext
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::messenger::MessengerPlaintext>
    for crate::messenger::MessengerPlaintext
{
    fn into_into_dart(self) -> crate::messenger::MessengerPlaintext {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::messenger::MessengerPreKey {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.pre_key_id.into_into_dart().into_dart(),
            self.public_key.into_into_dart().into_dart(),
            self.private_key.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::messenger::MessengerPreKey
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::messenger::MessengerPreKey>
    for crate::messenger::MessengerPreKey
{
    fn into_into_dart(self) -> crate::messenger::MessengerPreKey {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::messenger::MessengerPreKeyBundle {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.subject_did.into_into_dart().into_dart(),
            self.device_id.into_into_dart().into_dart(),
            self.identity_key.into_into_dart().into_dart(),
            self.signed_pre_key_id.into_into_dart().into_dart(),
            self.signed_pre_key.into_into_dart().into_dart(),
            self.signed_pre_key_signature.into_into_dart().into_dart(),
            self.one_time_pre_key_id.into_into_dart().into_dart(),
            self.one_time_pre_key.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::messenger::MessengerPreKeyBundle
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::messenger::MessengerPreKeyBundle>
    for crate::messenger::MessengerPreKeyBundle
{
    fn into_into_dart(self) -> crate::messenger::MessengerPreKeyBundle {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::atproto::did_plc::PlcGenesisOp {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.did.into_into_dart().into_dart(),
            self.genesis_json.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::atproto::did_plc::PlcGenesisOp
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::atproto::did_plc::PlcGenesisOp>
    for crate::atproto::did_plc::PlcGenesisOp
{
    fn into_into_dart(self) -> crate::atproto::did_plc::PlcGenesisOp {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api_zkp::ZkpResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.proof_hex.into_into_dart().into_dart(),
            self.nullifier_hex.into_into_dart().into_dart(),
            self.vk_hash.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api_zkp::ZkpResult {}
impl flutter_rust_bridge::IntoIntoDart<crate::api_zkp::ZkpResult> for crate::api_zkp::ZkpResult {
    fn into_into_dart(self) -> crate::api_zkp::ZkpResult {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::did_key::KeyPairBytes {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.private_key_hex, serializer);
        <String>::sse_encode(self.public_key_hex, serializer);
        <String>::sse_encode(self.did, serializer);
    }
}

impl SseEncode for crate::atproto::lexicon::LexiconRecord {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.type_, serializer);
        <String>::sse_encode(self.text, serializer);
        <String>::sse_encode(self.created_at, serializer);
        <Option<String>>::sse_encode(self.reply_to, serializer);
    }
}

impl SseEncode for Vec<crate::messenger::MessengerPreKey> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::messenger::MessengerPreKey>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::messenger::MessengerCiphertext {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.protocol_version, serializer);
        <String>::sse_encode(self.ciphertext_type, serializer);
        <Vec<u8>>::sse_encode(self.ciphertext, serializer);
        <String>::sse_encode(self.updated_session_state, serializer);
    }
}

impl SseEncode for crate::messenger::MessengerDevice {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.subject_did, serializer);
        <String>::sse_encode(self.device_id, serializer);
        <String>::sse_encode(self.identity_key_public, serializer);
        <String>::sse_encode(self.identity_key_private, serializer);
        <u32>::sse_encode(self.signed_pre_key_id, serializer);
        <String>::sse_encode(self.signed_pre_key_public, serializer);
        <String>::sse_encode(self.signed_pre_key_private, serializer);
        <String>::sse_encode(self.signed_pre_key_signature, serializer);
        <Option<String>>::sse_encode(self.session_state, serializer);
        <Vec<crate::messenger::MessengerPreKey>>::sse_encode(self.one_time_pre_keys, serializer);
        <u32>::sse_encode(self.next_pre_key_id, serializer);
    }
}

impl SseEncode for crate::messenger::MessengerEncryptInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::messenger::MessengerDevice>::sse_encode(self.local_device, serializer);
        <crate::messenger::MessengerPreKeyBundle>::sse_encode(self.remote_bundle, serializer);
        <Vec<u8>>::sse_encode(self.plaintext, serializer);
    }
}

impl SseEncode for crate::messenger::MessengerPlaintext {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.body, serializer);
        <String>::sse_encode(self.updated_session_state, serializer);
    }
}

impl SseEncode for crate::messenger::MessengerPreKey {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.pre_key_id, serializer);
        <String>::sse_encode(self.public_key, serializer);
        <String>::sse_encode(self.private_key, serializer);
    }
}

impl SseEncode for crate::messenger::MessengerPreKeyBundle {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.subject_did, serializer);
        <String>::sse_encode(self.device_id, serializer);
        <String>::sse_encode(self.identity_key, serializer);
        <u32>::sse_encode(self.signed_pre_key_id, serializer);
        <String>::sse_encode(self.signed_pre_key, serializer);
        <String>::sse_encode(self.signed_pre_key_signature, serializer);
        <u32>::sse_encode(self.one_time_pre_key_id, serializer);
        <String>::sse_encode(self.one_time_pre_key, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::atproto::did_plc::PlcGenesisOp {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.did, serializer);
        <String>::sse_encode(self.genesis_json, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api_zkp::ZkpResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.proof_hex, serializer);
        <String>::sse_encode(self.nullifier_hex, serializer);
        <String>::sse_encode(self.vk_hash, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.7.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;
