// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'did_key.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generate a new Ed25519 keypair. Returns private key hex + public key hex + DID string.
/// The caller MUST store private_key_hex in Secure Enclave / StrongBox immediately.
KeyPairBytes apiGenerateKeypair() =>
    RustLib.instance.api.crateApiApiGenerateKeypair();

/// Encode a hex-encoded Ed25519 public key as a did:key string.
String apiEncodeDidKey({required String publicKeyHex}) =>
    RustLib.instance.api.crateApiApiEncodeDidKey(publicKeyHex: publicKeyHex);

/// Decode a did:key string back to a hex-encoded public key.
String apiDecodeDidKey({required String did}) =>
    RustLib.instance.api.crateApiApiDecodeDidKey(did: did);

/// Sign a message. Both inputs and output are hex-encoded.
/// Run on a background thread (not #[frb(sync)]) to avoid blocking Dart UI.
Future<String> apiSignMessage({
  required String privateKeyHex,
  required String messageHex,
}) => RustLib.instance.api.crateApiApiSignMessage(
  privateKeyHex: privateKeyHex,
  messageHex: messageHex,
);

/// Verify an Ed25519 signature. All inputs are hex-encoded.
bool apiVerifySignature({
  required String publicKeyHex,
  required String messageHex,
  required String signatureHex,
}) => RustLib.instance.api.crateApiApiVerifySignature(
  publicKeyHex: publicKeyHex,
  messageHex: messageHex,
  signatureHex: signatureHex,
);
