// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `lock_docs`

/// Create or reset a Yrs document for [entityId].
void apiCrdtInitDoc({required String entityId}) =>
    RustLib.instance.api.crateApiCrdtApiCrdtInitDoc(entityId: entityId);

/// Insert text content into a named text field of a Yrs document.
///
/// Returns the base64-encoded binary delta to send as Op payload.
String apiCrdtInsertText({
  required String entityId,
  required String fieldName,
  required String content,
}) => RustLib.instance.api.crateApiCrdtApiCrdtInsertText(
  entityId: entityId,
  fieldName: fieldName,
  content: content,
);

/// Apply a received delta (base64 payload from an Op) to a local Yrs document.
void apiCrdtApplyDelta({
  required String entityId,
  required String payloadB64,
}) => RustLib.instance.api.crateApiCrdtApiCrdtApplyDelta(
  entityId: entityId,
  payloadB64: payloadB64,
);

/// Get the current text content for a named field of a Yrs document.
String apiCrdtGetText({required String entityId, required String fieldName}) =>
    RustLib.instance.api.crateApiCrdtApiCrdtGetText(
      entityId: entityId,
      fieldName: fieldName,
    );
