// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generate a Groth16 ZKP for a passport secret.
///
/// `passport_secret_hex` — 32-byte hex string (SHA-256 of MRZ fields).
///
/// Returns [ZkpResult] on success, or an error string.
Future<ZkpResult> apiZkpGenerateProof({required String passportSecretHex}) =>
    RustLib.instance.api.crateApiZkpApiZkpGenerateProof(
      passportSecretHex: passportSecretHex,
    );

/// Verify a Groth16 ZKP locally (for testing / dev mode).
Future<bool> apiZkpVerifyProof({
  required String proofHex,
  required String nullifierHex,
}) => RustLib.instance.api.crateApiZkpApiZkpVerifyProof(
  proofHex: proofHex,
  nullifierHex: nullifierHex,
);

/// Compute the anti-Sybil nullifier without generating a full ZKP.
///
/// Use only for dev/testing; production code should use [api_zkp_generate_proof]
/// which returns the nullifier as part of the full proof.
String apiZkpComputeNullifier({required String passportSecretHex}) => RustLib
    .instance
    .api
    .crateApiZkpApiZkpComputeNullifier(passportSecretHex: passportSecretHex);

/// Returned by [api_zkp_generate_proof].
class ZkpResult {
  /// Hex-encoded compressed Groth16 proof bytes.
  final String proofHex;

  /// Hex-encoded 32-byte anti-Sybil nullifier.
  final String nullifierHex;

  /// Hex-encoded SHA-256 hash of the Groth16 verifying key.
  /// The Relay validates this against its pinned ZKP key registry.
  final String vkHash;

  const ZkpResult({
    required this.proofHex,
    required this.nullifierHex,
    required this.vkHash,
  });

  @override
  int get hashCode =>
      proofHex.hashCode ^ nullifierHex.hashCode ^ vkHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZkpResult &&
          runtimeType == other.runtimeType &&
          proofHex == other.proofHex &&
          nullifierHex == other.nullifierHex &&
          vkHash == other.vkHash;
}
