// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'messenger.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

MessengerDevice apiMessengerCreateDevice({required String subjectDid}) =>
    RustLib.instance.api.crateApiMessengerApiMessengerCreateDevice(
      subjectDid: subjectDid,
    );

List<MessengerPreKey> apiMessengerGeneratePreKeys({
  required MessengerDevice device,
  required int count,
}) => RustLib.instance.api.crateApiMessengerApiMessengerGeneratePreKeys(
  device: device,
  count: count,
);

Future<MessengerCiphertext> apiMessengerEncryptInitialMessage({
  required MessengerEncryptInput input,
}) => RustLib.instance.api.crateApiMessengerApiMessengerEncryptInitialMessage(
  input: input,
);

Future<MessengerPlaintext> apiMessengerDecryptInboundMessage({
  required MessengerDevice localDevice,
  required MessengerCiphertext ciphertext,
}) => RustLib.instance.api.crateApiMessengerApiMessengerDecryptInboundMessage(
  localDevice: localDevice,
  ciphertext: ciphertext,
);
