// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'atproto/did_plc.dart';
import 'atproto/lexicon.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Encode a Lexicon record to DAG-CBOR bytes.
Future<Uint8List> apiCborEncodeRecord({required LexiconRecord record}) =>
    RustLib.instance.api.crateApiAtprotoApiCborEncodeRecord(record: record);

/// Compute CID v1 (DAG-CBOR, SHA2-256) from CBOR bytes.
String apiComputeCid({required List<int> cborBytes}) =>
    RustLib.instance.api.crateApiAtprotoApiComputeCid(cborBytes: cborBytes);

/// Sign a Repo commit: Ed25519(cbor_bytes), return hex signature.
Future<String> apiSignCommit({
  required List<int> cborBytes,
  required String privateKeyHex,
}) => RustLib.instance.api.crateApiAtprotoApiSignCommit(
  cborBytes: cborBytes,
  privateKeyHex: privateKeyHex,
);

/// Create a did:plc genesis op from an Ed25519 public key hex.
PlcGenesisOp apiCreateDidPlc({
  required String signingKeyHex,
  required String handle,
  required String pdsEndpoint,
}) => RustLib.instance.api.crateApiAtprotoApiCreateDidPlc(
  signingKeyHex: signingKeyHex,
  handle: handle,
  pdsEndpoint: pdsEndpoint,
);
