// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Keypair bytes returned to Dart.
/// Private key is hex-encoded; caller must store it in Secure Enclave / StrongBox.
class KeyPairBytes {
  final String privateKeyHex;
  final String publicKeyHex;
  final String did;

  const KeyPairBytes({
    required this.privateKeyHex,
    required this.publicKeyHex,
    required this.did,
  });

  @override
  int get hashCode =>
      privateKeyHex.hashCode ^ publicKeyHex.hashCode ^ did.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyPairBytes &&
          runtimeType == other.runtimeType &&
          privateKeyHex == other.privateKeyHex &&
          publicKeyHex == other.publicKeyHex &&
          did == other.did;
}
