// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api_atproto.dart';
import 'api_crdt.dart';
import 'api_messenger.dart';
import 'api_zkp.dart';
import 'atproto/did_plc.dart';
import 'atproto/lexicon.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'did_key.dart';
import 'frb_generated.dart';
import 'messenger.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  LexiconRecord dco_decode_box_autoadd_lexicon_record(dynamic raw);

  @protected
  MessengerCiphertext dco_decode_box_autoadd_messenger_ciphertext(dynamic raw);

  @protected
  MessengerDevice dco_decode_box_autoadd_messenger_device(dynamic raw);

  @protected
  MessengerEncryptInput dco_decode_box_autoadd_messenger_encrypt_input(
    dynamic raw,
  );

  @protected
  KeyPairBytes dco_decode_key_pair_bytes(dynamic raw);

  @protected
  LexiconRecord dco_decode_lexicon_record(dynamic raw);

  @protected
  List<MessengerPreKey> dco_decode_list_messenger_pre_key(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MessengerCiphertext dco_decode_messenger_ciphertext(dynamic raw);

  @protected
  MessengerDevice dco_decode_messenger_device(dynamic raw);

  @protected
  MessengerEncryptInput dco_decode_messenger_encrypt_input(dynamic raw);

  @protected
  MessengerPlaintext dco_decode_messenger_plaintext(dynamic raw);

  @protected
  MessengerPreKey dco_decode_messenger_pre_key(dynamic raw);

  @protected
  MessengerPreKeyBundle dco_decode_messenger_pre_key_bundle(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlcGenesisOp dco_decode_plc_genesis_op(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  ZkpResult dco_decode_zkp_result(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  LexiconRecord sse_decode_box_autoadd_lexicon_record(
    SseDeserializer deserializer,
  );

  @protected
  MessengerCiphertext sse_decode_box_autoadd_messenger_ciphertext(
    SseDeserializer deserializer,
  );

  @protected
  MessengerDevice sse_decode_box_autoadd_messenger_device(
    SseDeserializer deserializer,
  );

  @protected
  MessengerEncryptInput sse_decode_box_autoadd_messenger_encrypt_input(
    SseDeserializer deserializer,
  );

  @protected
  KeyPairBytes sse_decode_key_pair_bytes(SseDeserializer deserializer);

  @protected
  LexiconRecord sse_decode_lexicon_record(SseDeserializer deserializer);

  @protected
  List<MessengerPreKey> sse_decode_list_messenger_pre_key(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MessengerCiphertext sse_decode_messenger_ciphertext(
    SseDeserializer deserializer,
  );

  @protected
  MessengerDevice sse_decode_messenger_device(SseDeserializer deserializer);

  @protected
  MessengerEncryptInput sse_decode_messenger_encrypt_input(
    SseDeserializer deserializer,
  );

  @protected
  MessengerPlaintext sse_decode_messenger_plaintext(
    SseDeserializer deserializer,
  );

  @protected
  MessengerPreKey sse_decode_messenger_pre_key(SseDeserializer deserializer);

  @protected
  MessengerPreKeyBundle sse_decode_messenger_pre_key_bundle(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlcGenesisOp sse_decode_plc_genesis_op(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  ZkpResult sse_decode_zkp_result(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_lexicon_record(
    LexiconRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_messenger_ciphertext(
    MessengerCiphertext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_messenger_device(
    MessengerDevice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_messenger_encrypt_input(
    MessengerEncryptInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_key_pair_bytes(KeyPairBytes self, SseSerializer serializer);

  @protected
  void sse_encode_lexicon_record(LexiconRecord self, SseSerializer serializer);

  @protected
  void sse_encode_list_messenger_pre_key(
    List<MessengerPreKey> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_messenger_ciphertext(
    MessengerCiphertext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_messenger_device(
    MessengerDevice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_messenger_encrypt_input(
    MessengerEncryptInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_messenger_plaintext(
    MessengerPlaintext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_messenger_pre_key(
    MessengerPreKey self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_messenger_pre_key_bundle(
    MessengerPreKeyBundle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_plc_genesis_op(PlcGenesisOp self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_zkp_result(ZkpResult self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
