// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api_atproto.dart';
import 'api_crdt.dart';
import 'api_messenger.dart';
import 'api_zkp.dart';
import 'atproto/did_plc.dart';
import 'atproto/lexicon.dart';
import 'dart:async';
import 'dart:convert';
import 'did_key.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'messenger.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.7.0';

  @override
  int get rustContentHash => -411632102;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'ansible_rust_core',
        ioDirectory: '../../ansible_rust_core/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<Uint8List> crateApiAtprotoApiCborEncodeRecord({
    required LexiconRecord record,
  });

  String crateApiAtprotoApiComputeCid({required List<int> cborBytes});

  void crateApiCrdtApiCrdtApplyDelta({
    required String entityId,
    required String payloadB64,
  });

  String crateApiCrdtApiCrdtGetText({
    required String entityId,
    required String fieldName,
  });

  void crateApiCrdtApiCrdtInitDoc({required String entityId});

  String crateApiCrdtApiCrdtInsertText({
    required String entityId,
    required String fieldName,
    required String content,
  });

  PlcGenesisOp crateApiAtprotoApiCreateDidPlc({
    required String signingKeyHex,
    required String handle,
    required String pdsEndpoint,
  });

  String crateApiApiDecodeDidKey({required String did});

  String crateApiApiEncodeDidKey({required String publicKeyHex});

  KeyPairBytes crateApiApiGenerateKeypair();

  MessengerDevice crateApiMessengerApiMessengerCreateDevice({
    required String subjectDid,
  });

  Future<MessengerPlaintext>
  crateApiMessengerApiMessengerDecryptInboundMessage({
    required MessengerDevice localDevice,
    required MessengerCiphertext ciphertext,
  });

  Future<MessengerCiphertext>
  crateApiMessengerApiMessengerEncryptInitialMessage({
    required MessengerEncryptInput input,
  });

  List<MessengerPreKey> crateApiMessengerApiMessengerGeneratePreKeys({
    required MessengerDevice device,
    required int count,
  });

  Future<String> crateApiAtprotoApiSignCommit({
    required List<int> cborBytes,
    required String privateKeyHex,
  });

  Future<String> crateApiApiSignMessage({
    required String privateKeyHex,
    required String messageHex,
  });

  bool crateApiApiVerifySignature({
    required String publicKeyHex,
    required String messageHex,
    required String signatureHex,
  });

  String crateApiZkpApiZkpComputeNullifier({required String passportSecretHex});

  Future<ZkpResult> crateApiZkpApiZkpGenerateProof({
    required String passportSecretHex,
  });

  Future<bool> crateApiZkpApiZkpVerifyProof({
    required String proofHex,
    required String nullifierHex,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Uint8List> crateApiAtprotoApiCborEncodeRecord({
    required LexiconRecord record,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_lexicon_record(record, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAtprotoApiCborEncodeRecordConstMeta,
        argValues: [record],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAtprotoApiCborEncodeRecordConstMeta =>
      const TaskConstMeta(
        debugName: "api_cbor_encode_record",
        argNames: ["record"],
      );

  @override
  String crateApiAtprotoApiComputeCid({required List<int> cborBytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(cborBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAtprotoApiComputeCidConstMeta,
        argValues: [cborBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAtprotoApiComputeCidConstMeta =>
      const TaskConstMeta(
        debugName: "api_compute_cid",
        argNames: ["cborBytes"],
      );

  @override
  void crateApiCrdtApiCrdtApplyDelta({
    required String entityId,
    required String payloadB64,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(entityId, serializer);
          sse_encode_String(payloadB64, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCrdtApiCrdtApplyDeltaConstMeta,
        argValues: [entityId, payloadB64],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtApiCrdtApplyDeltaConstMeta =>
      const TaskConstMeta(
        debugName: "api_crdt_apply_delta",
        argNames: ["entityId", "payloadB64"],
      );

  @override
  String crateApiCrdtApiCrdtGetText({
    required String entityId,
    required String fieldName,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(entityId, serializer);
          sse_encode_String(fieldName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCrdtApiCrdtGetTextConstMeta,
        argValues: [entityId, fieldName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtApiCrdtGetTextConstMeta => const TaskConstMeta(
    debugName: "api_crdt_get_text",
    argNames: ["entityId", "fieldName"],
  );

  @override
  void crateApiCrdtApiCrdtInitDoc({required String entityId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(entityId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCrdtApiCrdtInitDocConstMeta,
        argValues: [entityId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtApiCrdtInitDocConstMeta => const TaskConstMeta(
    debugName: "api_crdt_init_doc",
    argNames: ["entityId"],
  );

  @override
  String crateApiCrdtApiCrdtInsertText({
    required String entityId,
    required String fieldName,
    required String content,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(entityId, serializer);
          sse_encode_String(fieldName, serializer);
          sse_encode_String(content, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCrdtApiCrdtInsertTextConstMeta,
        argValues: [entityId, fieldName, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrdtApiCrdtInsertTextConstMeta =>
      const TaskConstMeta(
        debugName: "api_crdt_insert_text",
        argNames: ["entityId", "fieldName", "content"],
      );

  @override
  PlcGenesisOp crateApiAtprotoApiCreateDidPlc({
    required String signingKeyHex,
    required String handle,
    required String pdsEndpoint,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(signingKeyHex, serializer);
          sse_encode_String(handle, serializer);
          sse_encode_String(pdsEndpoint, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_plc_genesis_op,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAtprotoApiCreateDidPlcConstMeta,
        argValues: [signingKeyHex, handle, pdsEndpoint],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAtprotoApiCreateDidPlcConstMeta =>
      const TaskConstMeta(
        debugName: "api_create_did_plc",
        argNames: ["signingKeyHex", "handle", "pdsEndpoint"],
      );

  @override
  String crateApiApiDecodeDidKey({required String did}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(did, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApiDecodeDidKeyConstMeta,
        argValues: [did],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiDecodeDidKeyConstMeta =>
      const TaskConstMeta(debugName: "api_decode_did_key", argNames: ["did"]);

  @override
  String crateApiApiEncodeDidKey({required String publicKeyHex}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(publicKeyHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApiEncodeDidKeyConstMeta,
        argValues: [publicKeyHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiEncodeDidKeyConstMeta => const TaskConstMeta(
    debugName: "api_encode_did_key",
    argNames: ["publicKeyHex"],
  );

  @override
  KeyPairBytes crateApiApiGenerateKeypair() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_key_pair_bytes,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiGenerateKeypairConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiGenerateKeypairConstMeta =>
      const TaskConstMeta(debugName: "api_generate_keypair", argNames: []);

  @override
  MessengerDevice crateApiMessengerApiMessengerCreateDevice({
    required String subjectDid,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(subjectDid, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_messenger_device,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMessengerApiMessengerCreateDeviceConstMeta,
        argValues: [subjectDid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessengerApiMessengerCreateDeviceConstMeta =>
      const TaskConstMeta(
        debugName: "api_messenger_create_device",
        argNames: ["subjectDid"],
      );

  @override
  Future<MessengerPlaintext>
  crateApiMessengerApiMessengerDecryptInboundMessage({
    required MessengerDevice localDevice,
    required MessengerCiphertext ciphertext,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_messenger_device(localDevice, serializer);
          sse_encode_box_autoadd_messenger_ciphertext(ciphertext, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_messenger_plaintext,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMessengerApiMessengerDecryptInboundMessageConstMeta,
        argValues: [localDevice, ciphertext],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiMessengerApiMessengerDecryptInboundMessageConstMeta =>
      const TaskConstMeta(
        debugName: "api_messenger_decrypt_inbound_message",
        argNames: ["localDevice", "ciphertext"],
      );

  @override
  Future<MessengerCiphertext>
  crateApiMessengerApiMessengerEncryptInitialMessage({
    required MessengerEncryptInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_messenger_encrypt_input(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_messenger_ciphertext,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMessengerApiMessengerEncryptInitialMessageConstMeta,
        argValues: [input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiMessengerApiMessengerEncryptInitialMessageConstMeta =>
      const TaskConstMeta(
        debugName: "api_messenger_encrypt_initial_message",
        argNames: ["input"],
      );

  @override
  List<MessengerPreKey> crateApiMessengerApiMessengerGeneratePreKeys({
    required MessengerDevice device,
    required int count,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_messenger_device(device, serializer);
          sse_encode_u_32(count, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_messenger_pre_key,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMessengerApiMessengerGeneratePreKeysConstMeta,
        argValues: [device, count],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMessengerApiMessengerGeneratePreKeysConstMeta =>
      const TaskConstMeta(
        debugName: "api_messenger_generate_pre_keys",
        argNames: ["device", "count"],
      );

  @override
  Future<String> crateApiAtprotoApiSignCommit({
    required List<int> cborBytes,
    required String privateKeyHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(cborBytes, serializer);
          sse_encode_String(privateKeyHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAtprotoApiSignCommitConstMeta,
        argValues: [cborBytes, privateKeyHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAtprotoApiSignCommitConstMeta =>
      const TaskConstMeta(
        debugName: "api_sign_commit",
        argNames: ["cborBytes", "privateKeyHex"],
      );

  @override
  Future<String> crateApiApiSignMessage({
    required String privateKeyHex,
    required String messageHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(privateKeyHex, serializer);
          sse_encode_String(messageHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApiSignMessageConstMeta,
        argValues: [privateKeyHex, messageHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiSignMessageConstMeta => const TaskConstMeta(
    debugName: "api_sign_message",
    argNames: ["privateKeyHex", "messageHex"],
  );

  @override
  bool crateApiApiVerifySignature({
    required String publicKeyHex,
    required String messageHex,
    required String signatureHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(publicKeyHex, serializer);
          sse_encode_String(messageHex, serializer);
          sse_encode_String(signatureHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiVerifySignatureConstMeta,
        argValues: [publicKeyHex, messageHex, signatureHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiVerifySignatureConstMeta => const TaskConstMeta(
    debugName: "api_verify_signature",
    argNames: ["publicKeyHex", "messageHex", "signatureHex"],
  );

  @override
  String crateApiZkpApiZkpComputeNullifier({
    required String passportSecretHex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(passportSecretHex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZkpApiZkpComputeNullifierConstMeta,
        argValues: [passportSecretHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZkpApiZkpComputeNullifierConstMeta =>
      const TaskConstMeta(
        debugName: "api_zkp_compute_nullifier",
        argNames: ["passportSecretHex"],
      );

  @override
  Future<ZkpResult> crateApiZkpApiZkpGenerateProof({
    required String passportSecretHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(passportSecretHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_zkp_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZkpApiZkpGenerateProofConstMeta,
        argValues: [passportSecretHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZkpApiZkpGenerateProofConstMeta =>
      const TaskConstMeta(
        debugName: "api_zkp_generate_proof",
        argNames: ["passportSecretHex"],
      );

  @override
  Future<bool> crateApiZkpApiZkpVerifyProof({
    required String proofHex,
    required String nullifierHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(proofHex, serializer);
          sse_encode_String(nullifierHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiZkpApiZkpVerifyProofConstMeta,
        argValues: [proofHex, nullifierHex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiZkpApiZkpVerifyProofConstMeta =>
      const TaskConstMeta(
        debugName: "api_zkp_verify_proof",
        argNames: ["proofHex", "nullifierHex"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  LexiconRecord dco_decode_box_autoadd_lexicon_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_lexicon_record(raw);
  }

  @protected
  MessengerCiphertext dco_decode_box_autoadd_messenger_ciphertext(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_messenger_ciphertext(raw);
  }

  @protected
  MessengerDevice dco_decode_box_autoadd_messenger_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_messenger_device(raw);
  }

  @protected
  MessengerEncryptInput dco_decode_box_autoadd_messenger_encrypt_input(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_messenger_encrypt_input(raw);
  }

  @protected
  KeyPairBytes dco_decode_key_pair_bytes(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return KeyPairBytes(
      privateKeyHex: dco_decode_String(arr[0]),
      publicKeyHex: dco_decode_String(arr[1]),
      did: dco_decode_String(arr[2]),
    );
  }

  @protected
  LexiconRecord dco_decode_lexicon_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return LexiconRecord(
      type: dco_decode_String(arr[0]),
      text: dco_decode_String(arr[1]),
      createdAt: dco_decode_String(arr[2]),
      replyTo: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  List<MessengerPreKey> dco_decode_list_messenger_pre_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_messenger_pre_key).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MessengerCiphertext dco_decode_messenger_ciphertext(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MessengerCiphertext(
      protocolVersion: dco_decode_String(arr[0]),
      ciphertextType: dco_decode_String(arr[1]),
      ciphertext: dco_decode_list_prim_u_8_strict(arr[2]),
      updatedSessionState: dco_decode_String(arr[3]),
    );
  }

  @protected
  MessengerDevice dco_decode_messenger_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return MessengerDevice(
      subjectDid: dco_decode_String(arr[0]),
      deviceId: dco_decode_String(arr[1]),
      identityKeyPublic: dco_decode_String(arr[2]),
      identityKeyPrivate: dco_decode_String(arr[3]),
      signedPreKeyId: dco_decode_u_32(arr[4]),
      signedPreKeyPublic: dco_decode_String(arr[5]),
      signedPreKeyPrivate: dco_decode_String(arr[6]),
      signedPreKeySignature: dco_decode_String(arr[7]),
      sessionState: dco_decode_opt_String(arr[8]),
      oneTimePreKeys: dco_decode_list_messenger_pre_key(arr[9]),
      nextPreKeyId: dco_decode_u_32(arr[10]),
    );
  }

  @protected
  MessengerEncryptInput dco_decode_messenger_encrypt_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MessengerEncryptInput(
      localDevice: dco_decode_messenger_device(arr[0]),
      remoteBundle: dco_decode_messenger_pre_key_bundle(arr[1]),
      plaintext: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  MessengerPlaintext dco_decode_messenger_plaintext(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MessengerPlaintext(
      body: dco_decode_list_prim_u_8_strict(arr[0]),
      updatedSessionState: dco_decode_String(arr[1]),
    );
  }

  @protected
  MessengerPreKey dco_decode_messenger_pre_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MessengerPreKey(
      preKeyId: dco_decode_u_32(arr[0]),
      publicKey: dco_decode_String(arr[1]),
      privateKey: dco_decode_String(arr[2]),
    );
  }

  @protected
  MessengerPreKeyBundle dco_decode_messenger_pre_key_bundle(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return MessengerPreKeyBundle(
      subjectDid: dco_decode_String(arr[0]),
      deviceId: dco_decode_String(arr[1]),
      identityKey: dco_decode_String(arr[2]),
      signedPreKeyId: dco_decode_u_32(arr[3]),
      signedPreKey: dco_decode_String(arr[4]),
      signedPreKeySignature: dco_decode_String(arr[5]),
      oneTimePreKeyId: dco_decode_u_32(arr[6]),
      oneTimePreKey: dco_decode_String(arr[7]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlcGenesisOp dco_decode_plc_genesis_op(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PlcGenesisOp(
      did: dco_decode_String(arr[0]),
      genesisJson: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  ZkpResult dco_decode_zkp_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ZkpResult(
      proofHex: dco_decode_String(arr[0]),
      nullifierHex: dco_decode_String(arr[1]),
      vkHash: dco_decode_String(arr[2]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  LexiconRecord sse_decode_box_autoadd_lexicon_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_lexicon_record(deserializer));
  }

  @protected
  MessengerCiphertext sse_decode_box_autoadd_messenger_ciphertext(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_messenger_ciphertext(deserializer));
  }

  @protected
  MessengerDevice sse_decode_box_autoadd_messenger_device(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_messenger_device(deserializer));
  }

  @protected
  MessengerEncryptInput sse_decode_box_autoadd_messenger_encrypt_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_messenger_encrypt_input(deserializer));
  }

  @protected
  KeyPairBytes sse_decode_key_pair_bytes(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_privateKeyHex = sse_decode_String(deserializer);
    var var_publicKeyHex = sse_decode_String(deserializer);
    var var_did = sse_decode_String(deserializer);
    return KeyPairBytes(
      privateKeyHex: var_privateKeyHex,
      publicKeyHex: var_publicKeyHex,
      did: var_did,
    );
  }

  @protected
  LexiconRecord sse_decode_lexicon_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_type = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_replyTo = sse_decode_opt_String(deserializer);
    return LexiconRecord(
      type: var_type,
      text: var_text,
      createdAt: var_createdAt,
      replyTo: var_replyTo,
    );
  }

  @protected
  List<MessengerPreKey> sse_decode_list_messenger_pre_key(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MessengerPreKey>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_messenger_pre_key(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MessengerCiphertext sse_decode_messenger_ciphertext(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_protocolVersion = sse_decode_String(deserializer);
    var var_ciphertextType = sse_decode_String(deserializer);
    var var_ciphertext = sse_decode_list_prim_u_8_strict(deserializer);
    var var_updatedSessionState = sse_decode_String(deserializer);
    return MessengerCiphertext(
      protocolVersion: var_protocolVersion,
      ciphertextType: var_ciphertextType,
      ciphertext: var_ciphertext,
      updatedSessionState: var_updatedSessionState,
    );
  }

  @protected
  MessengerDevice sse_decode_messenger_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_subjectDid = sse_decode_String(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    var var_identityKeyPublic = sse_decode_String(deserializer);
    var var_identityKeyPrivate = sse_decode_String(deserializer);
    var var_signedPreKeyId = sse_decode_u_32(deserializer);
    var var_signedPreKeyPublic = sse_decode_String(deserializer);
    var var_signedPreKeyPrivate = sse_decode_String(deserializer);
    var var_signedPreKeySignature = sse_decode_String(deserializer);
    var var_sessionState = sse_decode_opt_String(deserializer);
    var var_oneTimePreKeys = sse_decode_list_messenger_pre_key(deserializer);
    var var_nextPreKeyId = sse_decode_u_32(deserializer);
    return MessengerDevice(
      subjectDid: var_subjectDid,
      deviceId: var_deviceId,
      identityKeyPublic: var_identityKeyPublic,
      identityKeyPrivate: var_identityKeyPrivate,
      signedPreKeyId: var_signedPreKeyId,
      signedPreKeyPublic: var_signedPreKeyPublic,
      signedPreKeyPrivate: var_signedPreKeyPrivate,
      signedPreKeySignature: var_signedPreKeySignature,
      sessionState: var_sessionState,
      oneTimePreKeys: var_oneTimePreKeys,
      nextPreKeyId: var_nextPreKeyId,
    );
  }

  @protected
  MessengerEncryptInput sse_decode_messenger_encrypt_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_localDevice = sse_decode_messenger_device(deserializer);
    var var_remoteBundle = sse_decode_messenger_pre_key_bundle(deserializer);
    var var_plaintext = sse_decode_list_prim_u_8_strict(deserializer);
    return MessengerEncryptInput(
      localDevice: var_localDevice,
      remoteBundle: var_remoteBundle,
      plaintext: var_plaintext,
    );
  }

  @protected
  MessengerPlaintext sse_decode_messenger_plaintext(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_body = sse_decode_list_prim_u_8_strict(deserializer);
    var var_updatedSessionState = sse_decode_String(deserializer);
    return MessengerPlaintext(
      body: var_body,
      updatedSessionState: var_updatedSessionState,
    );
  }

  @protected
  MessengerPreKey sse_decode_messenger_pre_key(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_preKeyId = sse_decode_u_32(deserializer);
    var var_publicKey = sse_decode_String(deserializer);
    var var_privateKey = sse_decode_String(deserializer);
    return MessengerPreKey(
      preKeyId: var_preKeyId,
      publicKey: var_publicKey,
      privateKey: var_privateKey,
    );
  }

  @protected
  MessengerPreKeyBundle sse_decode_messenger_pre_key_bundle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_subjectDid = sse_decode_String(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    var var_identityKey = sse_decode_String(deserializer);
    var var_signedPreKeyId = sse_decode_u_32(deserializer);
    var var_signedPreKey = sse_decode_String(deserializer);
    var var_signedPreKeySignature = sse_decode_String(deserializer);
    var var_oneTimePreKeyId = sse_decode_u_32(deserializer);
    var var_oneTimePreKey = sse_decode_String(deserializer);
    return MessengerPreKeyBundle(
      subjectDid: var_subjectDid,
      deviceId: var_deviceId,
      identityKey: var_identityKey,
      signedPreKeyId: var_signedPreKeyId,
      signedPreKey: var_signedPreKey,
      signedPreKeySignature: var_signedPreKeySignature,
      oneTimePreKeyId: var_oneTimePreKeyId,
      oneTimePreKey: var_oneTimePreKey,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlcGenesisOp sse_decode_plc_genesis_op(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_did = sse_decode_String(deserializer);
    var var_genesisJson = sse_decode_String(deserializer);
    return PlcGenesisOp(did: var_did, genesisJson: var_genesisJson);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  ZkpResult sse_decode_zkp_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_proofHex = sse_decode_String(deserializer);
    var var_nullifierHex = sse_decode_String(deserializer);
    var var_vkHash = sse_decode_String(deserializer);
    return ZkpResult(
      proofHex: var_proofHex,
      nullifierHex: var_nullifierHex,
      vkHash: var_vkHash,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_lexicon_record(
    LexiconRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_lexicon_record(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_messenger_ciphertext(
    MessengerCiphertext self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_messenger_ciphertext(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_messenger_device(
    MessengerDevice self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_messenger_device(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_messenger_encrypt_input(
    MessengerEncryptInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_messenger_encrypt_input(self, serializer);
  }

  @protected
  void sse_encode_key_pair_bytes(KeyPairBytes self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.privateKeyHex, serializer);
    sse_encode_String(self.publicKeyHex, serializer);
    sse_encode_String(self.did, serializer);
  }

  @protected
  void sse_encode_lexicon_record(LexiconRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.type, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_opt_String(self.replyTo, serializer);
  }

  @protected
  void sse_encode_list_messenger_pre_key(
    List<MessengerPreKey> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_messenger_pre_key(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_messenger_ciphertext(
    MessengerCiphertext self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.protocolVersion, serializer);
    sse_encode_String(self.ciphertextType, serializer);
    sse_encode_list_prim_u_8_strict(self.ciphertext, serializer);
    sse_encode_String(self.updatedSessionState, serializer);
  }

  @protected
  void sse_encode_messenger_device(
    MessengerDevice self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.subjectDid, serializer);
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.identityKeyPublic, serializer);
    sse_encode_String(self.identityKeyPrivate, serializer);
    sse_encode_u_32(self.signedPreKeyId, serializer);
    sse_encode_String(self.signedPreKeyPublic, serializer);
    sse_encode_String(self.signedPreKeyPrivate, serializer);
    sse_encode_String(self.signedPreKeySignature, serializer);
    sse_encode_opt_String(self.sessionState, serializer);
    sse_encode_list_messenger_pre_key(self.oneTimePreKeys, serializer);
    sse_encode_u_32(self.nextPreKeyId, serializer);
  }

  @protected
  void sse_encode_messenger_encrypt_input(
    MessengerEncryptInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_messenger_device(self.localDevice, serializer);
    sse_encode_messenger_pre_key_bundle(self.remoteBundle, serializer);
    sse_encode_list_prim_u_8_strict(self.plaintext, serializer);
  }

  @protected
  void sse_encode_messenger_plaintext(
    MessengerPlaintext self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.body, serializer);
    sse_encode_String(self.updatedSessionState, serializer);
  }

  @protected
  void sse_encode_messenger_pre_key(
    MessengerPreKey self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.preKeyId, serializer);
    sse_encode_String(self.publicKey, serializer);
    sse_encode_String(self.privateKey, serializer);
  }

  @protected
  void sse_encode_messenger_pre_key_bundle(
    MessengerPreKeyBundle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.subjectDid, serializer);
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.identityKey, serializer);
    sse_encode_u_32(self.signedPreKeyId, serializer);
    sse_encode_String(self.signedPreKey, serializer);
    sse_encode_String(self.signedPreKeySignature, serializer);
    sse_encode_u_32(self.oneTimePreKeyId, serializer);
    sse_encode_String(self.oneTimePreKey, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_plc_genesis_op(PlcGenesisOp self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.did, serializer);
    sse_encode_String(self.genesisJson, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_zkp_result(ZkpResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.proofHex, serializer);
    sse_encode_String(self.nullifierHex, serializer);
    sse_encode_String(self.vkHash, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
