// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class MessengerCiphertext {
  final String protocolVersion;
  final String ciphertextType;
  final Uint8List ciphertext;
  final String updatedSessionState;

  const MessengerCiphertext({
    required this.protocolVersion,
    required this.ciphertextType,
    required this.ciphertext,
    required this.updatedSessionState,
  });

  @override
  int get hashCode =>
      protocolVersion.hashCode ^
      ciphertextType.hashCode ^
      ciphertext.hashCode ^
      updatedSessionState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessengerCiphertext &&
          runtimeType == other.runtimeType &&
          protocolVersion == other.protocolVersion &&
          ciphertextType == other.ciphertextType &&
          ciphertext == other.ciphertext &&
          updatedSessionState == other.updatedSessionState;
}

class MessengerDevice {
  final String subjectDid;
  final String deviceId;
  final String identityKeyPublic;
  final String identityKeyPrivate;
  final int signedPreKeyId;
  final String signedPreKeyPublic;
  final String signedPreKeyPrivate;
  final String signedPreKeySignature;
  final String? sessionState;
  final List<MessengerPreKey> oneTimePreKeys;
  final int nextPreKeyId;

  const MessengerDevice({
    required this.subjectDid,
    required this.deviceId,
    required this.identityKeyPublic,
    required this.identityKeyPrivate,
    required this.signedPreKeyId,
    required this.signedPreKeyPublic,
    required this.signedPreKeyPrivate,
    required this.signedPreKeySignature,
    this.sessionState,
    required this.oneTimePreKeys,
    required this.nextPreKeyId,
  });

  @override
  int get hashCode =>
      subjectDid.hashCode ^
      deviceId.hashCode ^
      identityKeyPublic.hashCode ^
      identityKeyPrivate.hashCode ^
      signedPreKeyId.hashCode ^
      signedPreKeyPublic.hashCode ^
      signedPreKeyPrivate.hashCode ^
      signedPreKeySignature.hashCode ^
      sessionState.hashCode ^
      oneTimePreKeys.hashCode ^
      nextPreKeyId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessengerDevice &&
          runtimeType == other.runtimeType &&
          subjectDid == other.subjectDid &&
          deviceId == other.deviceId &&
          identityKeyPublic == other.identityKeyPublic &&
          identityKeyPrivate == other.identityKeyPrivate &&
          signedPreKeyId == other.signedPreKeyId &&
          signedPreKeyPublic == other.signedPreKeyPublic &&
          signedPreKeyPrivate == other.signedPreKeyPrivate &&
          signedPreKeySignature == other.signedPreKeySignature &&
          sessionState == other.sessionState &&
          oneTimePreKeys == other.oneTimePreKeys &&
          nextPreKeyId == other.nextPreKeyId;
}

class MessengerEncryptInput {
  final MessengerDevice localDevice;
  final MessengerPreKeyBundle remoteBundle;
  final Uint8List plaintext;

  const MessengerEncryptInput({
    required this.localDevice,
    required this.remoteBundle,
    required this.plaintext,
  });

  @override
  int get hashCode =>
      localDevice.hashCode ^ remoteBundle.hashCode ^ plaintext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessengerEncryptInput &&
          runtimeType == other.runtimeType &&
          localDevice == other.localDevice &&
          remoteBundle == other.remoteBundle &&
          plaintext == other.plaintext;
}

class MessengerPlaintext {
  final Uint8List body;
  final String updatedSessionState;

  const MessengerPlaintext({
    required this.body,
    required this.updatedSessionState,
  });

  @override
  int get hashCode => body.hashCode ^ updatedSessionState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessengerPlaintext &&
          runtimeType == other.runtimeType &&
          body == other.body &&
          updatedSessionState == other.updatedSessionState;
}

class MessengerPreKey {
  final int preKeyId;
  final String publicKey;
  final String privateKey;

  const MessengerPreKey({
    required this.preKeyId,
    required this.publicKey,
    required this.privateKey,
  });

  @override
  int get hashCode =>
      preKeyId.hashCode ^ publicKey.hashCode ^ privateKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessengerPreKey &&
          runtimeType == other.runtimeType &&
          preKeyId == other.preKeyId &&
          publicKey == other.publicKey &&
          privateKey == other.privateKey;
}

class MessengerPreKeyBundle {
  final String subjectDid;
  final String deviceId;
  final String identityKey;
  final int signedPreKeyId;
  final String signedPreKey;
  final String signedPreKeySignature;
  final int oneTimePreKeyId;
  final String oneTimePreKey;

  const MessengerPreKeyBundle({
    required this.subjectDid,
    required this.deviceId,
    required this.identityKey,
    required this.signedPreKeyId,
    required this.signedPreKey,
    required this.signedPreKeySignature,
    required this.oneTimePreKeyId,
    required this.oneTimePreKey,
  });

  @override
  int get hashCode =>
      subjectDid.hashCode ^
      deviceId.hashCode ^
      identityKey.hashCode ^
      signedPreKeyId.hashCode ^
      signedPreKey.hashCode ^
      signedPreKeySignature.hashCode ^
      oneTimePreKeyId.hashCode ^
      oneTimePreKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessengerPreKeyBundle &&
          runtimeType == other.runtimeType &&
          subjectDid == other.subjectDid &&
          deviceId == other.deviceId &&
          identityKey == other.identityKey &&
          signedPreKeyId == other.signedPreKeyId &&
          signedPreKey == other.signedPreKey &&
          signedPreKeySignature == other.signedPreKeySignature &&
          oneTimePreKeyId == other.oneTimePreKeyId &&
          oneTimePreKey == other.oneTimePreKey;
}
