// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The result of a did:plc genesis operation.
class PlcGenesisOp {
  final String did;
  final String genesisJson;

  const PlcGenesisOp({required this.did, required this.genesisJson});

  @override
  int get hashCode => did.hashCode ^ genesisJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlcGenesisOp &&
          runtimeType == other.runtimeType &&
          did == other.did &&
          genesisJson == other.genesisJson;
}
