// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A minimal AT Protocol Lexicon record.
class LexiconRecord {
  final String type;
  final String text;
  final String createdAt;
  final String? replyTo;

  const LexiconRecord({
    required this.type,
    required this.text,
    required this.createdAt,
    this.replyTo,
  });

  @override
  int get hashCode =>
      type.hashCode ^ text.hashCode ^ createdAt.hashCode ^ replyTo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LexiconRecord &&
          runtimeType == other.runtimeType &&
          type == other.type &&
          text == other.text &&
          createdAt == other.createdAt &&
          replyTo == other.replyTo;
}
